packages:
  - "packages/*"
  - "apps/*"
  - "examples/*"
allowBuilds:
  '@google/genai': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  workerd: true
overrides:
  '@anvia/core': "workspace:*"
  apache-arrow: 18.1.0
