packages:
  - "packages/*"
  - "packages/*/*"
  - "apps/*"
  - "examples/*"
minimumReleaseAge: 10080
overrides:
  '@anvia/core': "workspace:*"
allowBuilds:
  '@google/genai': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  sharp: true
  workerd: true
